// ===== --- ===== ### FIFA-Referees ### ===== --- ===== //
const referees = [
  "Abdulrahman Al-Jassim",
  "Chris Beath",
  "Alireza Faghani",
  "Ma Ning",
  "Mohammed Abdulla Hassan Mohamed",
  "Yoshimi Yamashita",
  "Bakary Gassama",
  "Mustapha Ghorbal",
  "Victor Gomes",
  "Maguette Ndiaye",
  "Janny Sikazwe",
  "Salima Mukansanga",
  "Iván Barton",
  "Ismail Elfath",
  "Mario Escobar",
  "Saíd Martínez",
  "César Arturo Ramos",
  "Raphael Claus",
  "Andrés Matonte",
  "Kevin Ortega",
  "Fernando Rapallini",
  "Facundo Tello",
  "Jesús Valenzuela",
  "Wilton Sampaio",
  "Matthew Conger",
  "István Kovács",
  "Danny Makkelie",
  "Szymon Marciniak",
  "Antonio Mateu Lahoz",
  "Michael Oliver",
  "Daniele Orsato",
  "Daniel Siebert",
  "Anthony Taylor",
  "Clément Turpin",
  "Slavko Vinčić",
  "Stéphanie Frappart",
];

// ===== --- ===== ### FIFA-Assistant-Referees ### ===== --- ===== //
const assistantReferees = [
  "Taleb Al-Marri",
  "Saud Al-Maqaleh",
  "Anton Shchetinin",
  "Ashley Beecham",
  "Mohammadreza Mansouri",
  "Mohammadreza Abolfazli",
  "Cao Yi",
  "Shi Xiang",
  "Mohamed Al-Hammadi",
  "Hasan Al-Mahri",
  "Elvis Noupue",
  "Mahmoud Abouelregal",
  "Mokrane Gourari",
  "Abdelhak Etchiali",
  "Zakhele Siwela",
  "Souru Phatsoane",
  "Djibril Camara",
  "El Hadj Malick Samba",
  "Jerson dos Santos",
  "Arsénio Marrengula",
  "David Morán",
  "Zachari Zeegelaar",
  "Kathryn Nesbitt",
  "Kyle Atkins",
  "Corey Parker",
  "Caleb Wales",
  "Juan Carlos Mora",
  "Walter López",
  "Helpys Raymundo Feliz",
  "Alberto Morín",
  "Miguel Hernández",
  "Rodrigo Figueiredo",
  "Danilo Manis",
  "Nicolás Taran",
  "Martín Soppi",
  "Michael Orué",
  "Jesús Sánchez",
  "Juan Pablo Belatti",
  "Diego Bonfá",
  "Ezequiel Brailovsky",
  "Gabriel Chade",
  "Jorge Urrego",
  "Tulio Moreno",
  "Bruno Boschilia",
  "Bruno Pires",
  "Mark Rule",
  "Tevita Makasini",
  "Ovidiu Artene",
  "Vasile Marinescu",
  "Hessel Steegstra",
  "Jan de Vries",
  "Paweł Sokolnicki",
  "Tomasz Listkiewicz",
  "Pau Cebrián Devís",
  "Roberto Díaz Pérez del Palomar",
  "Stuart Burt",
  "Simon Bennett",
  "Gary Beswick",
  "Ciro Carbone",
  "Alessandro Giallatini",
  "Rafael Foltyn",
  "Jan Seidel",
  "Gary Beswick",
  "Adam Nunn",
  "Nicolas Danos",
  "Cyril Gringore",
  "Tomaž Klančnik",
  "Andraž Kovačič",
  "Neuza Back",
  "Karen Díaz Medina",
];

// ===== --- ===== ### FIFA-Var-Assistant-Referees ### ===== --- ===== //
const varAssistantReferees = [
  "Abdulla Al-Marri",
  "Muhammad Taqi",
  "Shaun Evans",
  "Rédouane Jiyed",
  "Adil Zourak",
  "Drew Fischer",
  "Fernando Guerrero",
  "Armando Villarreal",
  "Julio Bascuñán",
  "Nicolás Gallo",
  "Leodán González",
  "Juan Soto",
  "Mauro Vigliano",
  "Jérôme Brisard",
  "Bastian Dankert",
  "Ricardo de Burgos Bengoetxea",
  "Marco Fritz",
  "Alejandro Hernández Hernández",
  "Massimiliano Irrati",
  "Tomasz Kwiatkowski",
  "Juan Martínez Munuera",
  "Benoît Millot",
  "Paolo Valeri",
  "Pol van Boekel",
];

export { referees, assistantReferees, varAssistantReferees };
